#!/bin/sh
# Get the NFS Server running

# Connect to the servers and prepare them
yum install -y nfs-utils
mkdir /data
echo "# This is a static content generated by provision_nfs_server" > /etc/exports
echo "/data 17.0.0.0/8(rw,sync,no_root_squash,no_subtree_check)" >> /etc/exports
service rpcbind start
service nfs start
